[package]
name = "najm-course-entities"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
serde.workspace = true
surrealdb.workspace = true
thiserror.workspace = true
utoipa.workspace = true
